### ISSUE TITLE
Preference > Absorption Settings > Advanced entries missing

### ISSUE THREAD

**Issue by mountrcg** [ga-zelle/autoISF#1]
I can't see the 2 options for 
- autoisf_hourlychange
- autoisf_max 
underneath the settings for max and min autosense_ratio. Everything else is there in the Preference > OpenAPS SMB. Also checked the adjusted file (pref_absorption_oref1) for the entries, they are there. Could it be that it also has to be done in pref_absorption_aaps.xml?

**Comment by mountrcg** [comment]
I just put the additional parts from pref_absorption_oref1.xml also in pref_absorption_aaps.xml and they do show up. Will test later in SMB results whether changes will be accepted. Running on freeaps x momentarily and preparing for pod change back into AndroidAPS with UAM.

**Comment by ga-zelle** [comment]
These two are contained in Absorption Settings, not SMB. But, may be it is a special situation in freeaps.

**Comment by mountrcg** [comment]
Ich hatte deine Anpassungen in AAPS 2.8.2 integriert. In den Absorption settings taucht wenn ich 

- autoisf_hourlychange
- autoisf_max

wie bei dir in dem File pref_absorption_oref1.xml integriere eben nicht auf. Schmeiße ich die beiden Einträge dazu jedoch in das File pref_absorption_aaps.xml , dann tauchen sie auch in den Einstellungen auf und ich kann anpassen.

**Comment by ga-zelle** [comment]
Also  da bist du der erste, der das berichtet. Machen, die die Änderungen nicht im AS sondern durch Austausch der Files gemacht hatten, passierte es, daß sie im ertsen Versuch den falschen strings.xml erwischten.

Die Files mit "oref1" beziehen sich normalerweise auf die SMB Version, ansonsten auf die mit AMA. Wenn es bei dir auch mit AMA funktioniert - um so besser.

**Comment by mountrcg** [comment]
also ich musste auf alle Fälle  auf den commit [a4c8452f595bd77c3f39c4fc1b2ee54162da559e](https://github.com/mountrcg/AndroidAPS/commit/a4c8452f595bd77c3f39c4fc1b2ee54162da559e) noch diesen drauf satteln um in den Settings was ändern zu können [c99dddb37d2790de24374b5a546eb9a7588d5ae5](https://github.com/mountrcg/AndroidAPS/commit/c99dddb37d2790de24374b5a546eb9a7588d5ae5), vorher waren die Einträge nicht da. Ich teste es morgen nochmals ohne das 2. File.

**Comment by mountrcg** [comment]
OK so wieder auf AAPS. Ich bin jetzt gerade in der Version ohne die Anpassungen in pref_absorption_aaps.xml , also wie von Dir bereitgestellt. Ich sehe meine Anpassungen der beiden Faktoren

- autoisf_hourlychange
- autoisf_max

die ich in der AAPS-Version zuvor mit den Ergänzungen in pref_absorption_aaps.xml gemacht hatte. Tauchen bei SMB > Profile auf. In den Preferences > Absorption Settings > Advanced eben jedoch nicht. Mit fällt aber auf, dass in den SMB > Constraints folgendes steht 
`Safety: UAM disabled because it rely on Oref1 sensitivity plugin`
 UAM ist aktiviert, falls nicht würde noch ein anderer Constraint angezeigt werden. Suche gerade was das auslöst, bisher wenig darüber zu finden. SMB's und Sensitivity sind alle an.

**Comment by mountrcg** [comment]
Ok, mein Fehler - war im Config Builder noch auf Sensitivity Weighted Average statt Oref1. Jetzt erscheinen auch Deine Optionen in Preferences > Absorption Settings > Advanced
